name: release
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: "./.github/actions/will-release-check"
      - name: Set git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "SHIP IT"
      - run: npm i
      - name: Generate the stylesheet file
        run: npm run generate
      - run: cat index.css
      - name: bump version
        run: npm version ${WILL_RELEASE_TYPE}
      - name: create .npmrc
        run: echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} > .npmrc
      - run: cat .npmrc
      - name: npm publish
        run: npm publish
      - name: Push changes
        uses: "./.github/actions/git-push-action"
        with:
          branch: master
          github_token: ${{ secrets.UNI_PUSH_TOKEN }}
